### ISSUE TITLE
The project doesn't build

### ISSUE THREAD

**Issue by fbuedding** [bfi-de/ngsild-grafana-datasource#4]
Since the release doesn't contain the newest changes which would fix some issues I tried to build the plugin myself.

Both the docker workflow and node workflow are not working.

For every input the following Error occurs: 
`TS2739: Type '{ value: number; onChange: (evt: FormEvent<HTMLInputElement>) => void; type: string; width: number; title: string; }' is
 missing the following properties from type 'Pick<Props$13, "key" | "type" | "min" | "max" | "children" | "className" | "cite" | "data" | "for
m" | "label" | "slot" | "span" | "style" | "summary" | "title" | "pattern" | ... 347 more ... | "addonAfter">': onPointerEnterCapture, onPoint
erLeaveCapture`

Thank you

**Comment by cnoelle** [comment]
Thanks for reporting. I couldn't reproduce the build problem in either workflow, so far. Can you provide the full stack trace for the error?

In any case, I will create a new release with the last fixes. It will require some updates, though, due to incompatibilities with the latest versions of the tools used in the example.

**Comment by cnoelle** [comment]
Finally, I could reproduce the issue. It is fixed now, and there is a new release: https://github.com/bfi-de/ngsild-grafana-datasource/releases/tag/v1.1.0

**Comment by fbuedding** [comment]
Thank you so much! Sorry for not getting back yesterday!

One more thing: The Grafana CLI supports adding plugins from a URL pointing to a zipped plugin. As far as I can see the release is containing a [tgz](https://github.com/bfi-de/ngsild-grafana-datasource/releases/download/v1.1.0/ngsild-grafana-datasource-1.1.0.tgz) archive which has correct files in it. So if you were to release it as a zip archive it would be installable via the grafana cli (I think).

Thank you for your efforts!

**Comment by cnoelle** [comment]
@fbuedding : thank you for the pointer to the Grafana CLI, I wasn't aware of it. There is a new issue for these kind of "modernisations" in terms of Grafana tooling: https://github.com/bfi-de/ngsild-grafana-datasource/issues/5

**Comment by fbuedding** [comment]
Okay should I comment there again?

**Comment by fbuedding** [comment]
@cnoelle 

I still can't build the build/dev the project. Installing works.

OS:
```
ProductName:		macOS
ProductVersion:		15.0.1
BuildVersion:		24A348
```
Node version: `v20.18.0`
Yarn version: `4.5.1`
Command: `yarn dev`
Output:
[log.txt](https://github.com/user-attachments/files/17557620/log.txt)

**Comment by cnoelle** [comment]
> Okay should I comment there again?

Not necessary, the zip file is available now and usage instructions are here: https://github.com/bfi-de/ngsild-grafana-datasource?tab=readme-ov-file#alternative-2-use-the-grafana-cli

**Comment by fbuedding** [comment]
> > Okay should I comment there again?
> 
> Not necessary, the zip file is available now and usage instructions are here: https://github.com/bfi-de/ngsild-grafana-datasource?tab=readme-ov-file#alternative-2-use-the-grafana-cli

I also just tested installing the plugin via the grafana cli and it works.

Command (`<version>` need to be replaced with 1.1.1): 
```bash
grafana cli --pluginUrl https://github.com/bfi-de/ngsild-grafana-datasource/releases/download/v<version>/ngsild-grafana-datasource-<version>.zip plugins install ngsild-grafana-datasource
```

**Comment by cnoelle** [comment]
Migrated from yarn to npm as build tool. For some reason the yarn commands modified the tsconfig.json file and hence led to the observed build errors. On the downside, npm is much slower, in particular `npm install`. 

New build instructions: `npm install` (once) followed by `npm run build`.

**Comment by fbuedding** [comment]
I can confirm that it builds. I'll test later if the builded plugin works. 

Thank you!
